from mailmerge import MailMerge
from datetime import date
template = ("Seguimiento_plantilla.docx")
document = MailMerge(template)
print(document.get_merge_fields())
{'PLAN', 'ESPECIALIDAD', 'NOMBRE', 'MODALIDAD', 'MATRICULA', 'CARRERA', 'PERIODO', 'PERIODO2', 'CLAVE1', 'CLAVE2', 'CLAVE3', 'CLAVE4', 'CLAVE5', 'CLAVE6', 'MATERIA1','MATERIA2', 'MATERIA3', 'MATERIA4', 'MATERIA5', 'MATERIA6','CRD1', 'CRD2', 'CRD3' , 'CRD4' , 'CRD5' , 'CRD6' , 'CAL1' , 'CAL2' , 'CAL3' , 'CAL4' , 'CAL5' , 'CAL6' , 'EXAMEN1' , 'EXAMEN2', 'EXAMEN3', 'EXAMEN4', 'EXAMEN5', 'EXAMEN6','CURSO1','CURSO2','CURSO3','CURSO4','CURSO5','CURSO6'}
document . merge ( 
PLAN = 'IELC-2010-2011',
ESPECIALIDAD = 'MECATRONICA INDUSTRIAL',
NOMBRE = 'GILBERTO ENMANUEL GONZÁLEZ CAJUN',
MATRICULA = 'E16082057',
CARRERA = 'ING. ELECTRÓNICA',
MODALIDAD = 'ESCOLARIZADA', 
PERIODO= '22/08/2016', 
PERIODO2 = '16/12/2016',
CLAVE1 = 'ACA-0907', 
CLAVE2 ='ACC-0906', 
CLAVE3 = 'ACF-0901',
CLAVE4 = 'AEC-1058',
CLAVE5 ='AEF-1042', 
CLAVE6 = 'AEQ-1387',
MATERIA1 = 'TALLER DE ÉTICA',
MATERIA2 = 'FUNCAMENTOS DE INVESTIGACIÓN',
MATERIA3 = 'CÁLCULO DIFERENCIAL', 
MATERIA4 = 'QUÍMICA',
MATERIA5 = 'MECÁNICA CLÁSICA',
MATERIA6 = 'COMUNICACIÓN HUMANA',
CRD1 = '4',
CRD2 = '4',
CRD3 = '5',
CRD4 = '4',
CRD5 = '5',
CRD6 = '3',
CAL1 = '100',
CAL2 = '100',
CAL3 = '100',
CAL4 = '100',
CAL5 = '100',
CAL6 = '100',
EXAMEN1 = 'CN',
EXAMEN2 = 'CN',
EXAMEN3 = 'CN',
EXAMEN4 = 'CN',
EXAMEN5 = 'CN',
EXAMEN6 = 'CN',
CURSO1 = 'CO',
CURSO2 = 'CO',
CURSO3 = 'CO',
CURSO4 = 'CO',
CURSO5 = 'CO',
CURSO6 = 'CO',)

document.write('SEGUIMIENTO-EJEMPLO.docx')
